# Generated by Django 5.0.7 on 2024-07-20 10:16

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(default="Admin", max_length=100)),
                ("img", models.ImageField(upload_to="Images")),
                ("content", models.TextField()),
                (
                    "blog_slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "PUBLISH"), ("0", "DRAFT")],
                        default=0,
                        max_length=1,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("Trending", "Trending"),
                            ("Popular", "Popular"),
                            ("Recent", "Recent"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Main_post", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="home.category",
                    ),
                ),
            ],
        ),
    ]
