# Generated by Django 5.0.7 on 2024-07-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("0", "DRAFT"), ("1", "PUBLISH")], default=0, max_length=1
            ),
        ),
    ]
