# Generated by Django 5.0.7 on 2024-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_comment_post_alter_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="blog",
            name="section",
            field=models.CharField(
                choices=[
                    ("Trending", "Trending"),
                    ("Popular", "Popular"),
                    ("Recent", "Recent"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("0", "DRAFT"), ("1", "PUBLISH")], default=0, max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
